export const thaiLessons = {
  vocabulary: {
    verbs: {
      พูด: {
        romanized: "pôot",
        chinese: "说",
        english: "to speak/say",
        type: "verb",
        usage_notes: "Used for general speaking. More formal than 'บอก'",
        common_patterns: [
          "พูด + ภาษา (speak a language)",
          "พูด + ว่า (say that...)",
        ],
      },
      อยู่: {
        romanized: "yùu",
        chinese: "在",
        english: "to be (located)/to stay",
        type: "verb",
        usage_notes: "Used for location and continuous actions",
        common_patterns: [
          "อยู่ + ที่ (to be at)",
          "กำลัง + verb + อยู่ (currently doing)",
        ],
      },
      ไป: {
        romanized: "bpai",
        chinese: "去",
        english: "to go",
        type: "verb",
        usage_notes: "Also used as directional particle",
        common_patterns: [
          "ไป + ที่ (go to)",
          "verb + ไป (action away from speaker)",
        ],
      },
      มา: {
        romanized: "maa",
        chinese: "来",
        english: "to come",
        type: "verb",
        usage_notes: "Also used as directional particle",
        common_patterns: [
          "มา + จาก (come from)",
          "verb + มา (action towards speaker)",
        ],
      },
      กิน: {
        romanized: "gin",
        chinese: "吃",
        english: "to eat",
        type: "verb",
        usage_notes: "Casual form, ทาน is more polite",
        common_patterns: [
          "กิน + ข้าว (eat rice/meal)",
          "กิน + อาหาร (eat food)",
        ],
      },
      ดื่ม: {
        romanized: "dʉ̀ʉm",
        chinese: "喝",
        english: "to drink",
        type: "verb",
        usage_notes: "Used for all beverages",
        common_patterns: [
          "ดื่ม + น้ำ (drink water)",
          "ดื่ม + กาแฟ (drink coffee)",
        ],
      },
      เรียน: {
        romanized: "rian",
        chinese: "学习",
        english: "to study/learn",
        type: "verb",
        usage_notes: "Used for formal learning",
        common_patterns: [
          "เรียน + ภาษา (study language)",
          "เรียน + ที่ (study at)",
        ],
      },
      นอน: {
        romanized: "nɔɔn",
        chinese: "睡觉",
        english: "to sleep",
        type: "verb",
        usage_notes: "Also means 'to lie down'",
        common_patterns: ["นอน + หลับ (fall asleep)", "นอน + ที่ (sleep at)"],
      },
      ทำงาน: {
        romanized: "tam-ngaan",
        chinese: "工作",
        english: "to work",
        type: "verb",
        usage_notes: "Compound of ทำ (do) + งาน (work)",
        common_patterns: ["ทำงาน + ที่ (work at)", "ทำงาน + กับ (work with)"],
      },
    },
    nouns: {
      ห้องน้ำ: {
        romanized: "hông-náam",
        chinese: "厕所",
        english: "bathroom",
        type: "noun",
        literal: "water room",
        components: ["ห้อง (room)", "น้ำ (water)"],
      },
      ภาษา: {
        romanized: "paa-săa",
        chinese: "语言",
        english: "language",
        type: "noun",
        common_compounds: [
          "ภาษาไทย (Thai)",
          "ภาษาจีน (Chinese)",
          "ภาษาอังกฤษ (English)",
        ],
      },
      ร้านอาหาร: {
        romanized: "ráan-aa-hăan",
        chinese: "餐厅",
        english: "restaurant",
        type: "noun",
        literal: "food shop",
        components: ["ร้าน (shop)", "อาหาร (food)"],
      },
      โรงเรียน: {
        romanized: "roong-rian",
        chinese: "学校",
        english: "school",
        type: "noun",
        literal: "learning building",
        components: ["โรง (building)", "เรียน (learn)"],
      },
      ตลาด: {
        romanized: "dtà-làat",
        chinese: "市场",
        english: "market",
        type: "noun",
        usage_notes: "Often refers to fresh markets",
      },
      สถานีรถไฟ: {
        romanized: "sà-tăa-nee-rót-fai",
        chinese: "火车站",
        english: "train station",
        type: "noun",
        components: ["สถานี (station)", "รถไฟ (train)"],
      },
    },
    question_words: {
      ที่ไหน: {
        romanized: "têe-năi",
        chinese: "哪里",
        english: "where",
        type: "question word",
        usage_notes: "Used for asking about location",
        common_patterns: ["อยู่ + ที่ไหน (where is)", "ไป + ที่ไหน (where go)"],
      },
      ยังไง: {
        romanized: "yang-ngai",
        chinese: "怎么",
        english: "how",
        type: "question word",
        usage_notes: "Used for asking about method or manner",
        common_patterns: ["ทำ + ยังไง (how to do)", "พูด + ยังไง (how to say)"],
      },
      เมื่อไหร่: {
        romanized: "mʉ̂a-rai",
        chinese: "什么时候",
        english: "when",
        type: "question word",
        usage_notes: "Used for asking about time",
        common_patterns: [
          "จะ + verb + เมื่อไหร่ (when will...)",
          "มา + เมื่อไหร่ (when come)",
        ],
      },
      ทำไม: {
        romanized: "tam-mai",
        chinese: "为什么",
        english: "why",
        type: "question word",
        usage_notes: "Used for asking about reasons",
        common_patterns: ["ทำไม + จึง (why then)", "ทำไม + ถึง (why so)"],
      },
      อะไร: {
        romanized: "a-rai",
        chinese: "什么",
        english: "what",
        type: "question word",
        usage_notes: "Used for asking about things",
        common_patterns: [
          "นี่ + คือ + อะไร (what is this)",
          "กิน + อะไร (what eat)",
        ],
      },
      ใคร: {
        romanized: "krai",
        chinese: "谁",
        english: "who",
        type: "question word",
        usage_notes: "Used for asking about people",
        common_patterns: [
          "นั่น + คือ + ใคร (who is that)",
          "ใคร + ทำ (who did)",
        ],
      },
    },
    pronouns: {
      นี่: {
        romanized: "nêe",
        chinese: "这",
        english: "this",
        type: "pronoun",
        usage_notes: "Demonstrative pronoun, close to speaker",
        related: ["นั่น (that - middle distance)", "โน่น (that - far away)"],
      },
      คุณ: {
        romanized: "khun",
        chinese: "你",
        english: "you",
        type: "pronoun",
        usage_notes: "Polite form of 'you'",
        register: "formal/polite",
      },
      ผม: {
        romanized: "pǒm",
        chinese: "我",
        english: "I (masculine)",
        type: "pronoun",
        usage_notes: "Polite male first-person pronoun",
        register: "formal/polite",
      },
      ดิฉัน: {
        romanized: "di-chǎn",
        chinese: "我",
        english: "I (feminine)",
        type: "pronoun",
        usage_notes: "Polite female first-person pronoun",
        register: "formal/polite",
      },
      เขา: {
        romanized: "kháo",
        chinese: "他/她",
        english: "he/she",
        type: "pronoun",
        usage_notes: "Gender-neutral third-person pronoun",
        register: "neutral",
      },
      พวกเขา: {
        romanized: "pûak-kháo",
        chinese: "他们/她们",
        english: "they",
        type: "pronoun",
        usage_notes: "Plural third-person pronoun",
        components: ["พวก (group)", "เขา (he/she)"],
      },
    },
  },
  questions: {
    where: [
      {
        segments: [
          {
            thai: ["ห้อง", "น้ำ"],
            romanized: ["hông", "náam"],
            chinese: "厕所",
            english: "bathroom",
            type: "noun",
            color: "text-red-500",
          },
          {
            thai: ["อยู่"],
            romanized: ["yùu"],
            chinese: "在",
            english: "is",
            type: "verb",
            color: "text-blue-500",
          },
          {
            thai: ["ที่", "ไหน"],
            romanized: ["tee", "nai"],
            chinese: "哪里",
            english: "where",
            type: "question word",
            color: "text-green-500",
          },
        ],
        english: "Where is the bathroom?",
        english_segments: ["where", "is", "the bathroom"],
        literal_chinese: {
          text: ["厕所", "在", "哪里"],
          colors: ["text-red-500", "text-blue-500", "text-green-500"],
        },
        natural_chinese: "洗手间在哪里？",
        grammar_point: "Location questions with อยู่ที่ไหน",
        key_vocab: {
          "ห้อง-น้ำ": "bathroom (noun: lit. water room)",
          อยู่: "to be located (verb)",
          "ที่-ไหน": "where (question word)",
        },
      },
      {
        segments: [
          {
            thai: ["ร้าน", "อาหาร"],
            romanized: ["ráan", "aa-hăan"],
            chinese: "餐厅",
            english: "restaurant",
            type: "noun",
            color: "text-red-500",
          },
          {
            thai: ["อยู่"],
            romanized: ["yùu"],
            chinese: "在",
            english: "is",
            type: "verb",
            color: "text-blue-500",
          },
          {
            thai: ["ที่", "ไหน"],
            romanized: ["tee", "nai"],
            chinese: "哪里",
            english: "where",
            type: "question word",
            color: "text-green-500",
          },
        ],
        english: "Where is the restaurant?",
        english_segments: ["where", "is", "the restaurant"],
        literal_chinese: {
          text: ["餐厅", "在", "哪里"],
          colors: ["text-red-500", "text-blue-500", "text-green-500"],
        },
        natural_chinese: "餐厅在哪里？",
        grammar_point: "Location questions with อยู่ที่ไหน",
        key_vocab: {
          "ร้าน-อาหาร": "restaurant (noun: lit. food shop)",
          อยู่: "to be located (verb)",
          "ที่-ไหน": "where (question word)",
        },
      },
      {
        segments: [
          {
            thai: ["สถานี", "รถไฟ"],
            romanized: ["sà-tăa-nee", "rót-fai"],
            chinese: "火车站",
            english: "train station",
            type: "noun",
            color: "text-red-500",
          },
          {
            thai: ["ยยู่"],
            romanized: ["yùu"],
            chinese: "在",
            english: "is",
            type: "verb",
            color: "text-blue-500",
          },
          {
            thai: ["ที่", "ไหน"],
            romanized: ["tee", "nai"],
            chinese: "哪里",
            english: "where",
            type: "question word",
            color: "text-green-500",
          },
        ],
        english: "Where is the train station?",
        english_segments: ["where", "is", "the train station"],
        literal_chinese: {
          text: ["火车站", "在", "哪里"],
          colors: ["text-red-500", "text-blue-500", "text-green-500"],
        },
        natural_chinese: "火车站在哪里？",
        grammar_point: "Location questions with อยู่ที่ไหน",
        key_vocab: {
          "สถานี-รถไฟ": "train station (noun)",
          อยู่: "to be located (verb)",
          "ที่-ไหน": "where (question word)",
        },
      },
    ],
    how: [
      {
        segments: [
          {
            thai: ["นี่"],
            romanized: ["nêe"],
            chinese: "这",
            english: "this",
            type: "pronoun",
            color: "text-purple-500",
          },
          {
            thai: ["พูด"],
            romanized: ["pôot"],
            chinese: "说",
            english: "say",
            type: "verb",
            color: "text-blue-500",
          },
          {
            thai: ["ภาษา", "ไทย"],
            romanized: ["paa-săa", "tai"],
            chinese: "Bahasa Thai",
            english: "Bahasa Thai",
            type: "noun",
            color: "text-red-500",
          },
          {
            thai: ["ยัง", "ไง"],
            romanized: ["yang", "ngai"],
            chinese: "怎么",
            english: "how",
            type: "question word",
            color: "text-green-500",
          },
        ],
        english: "How do you speak Thai?",
        english_segments: ["how", "speak", "Thai"],
        literal_chinese: {
          text: ["怎么说", "泰语"],
          colors: ["text-green-500", "text-blue-500", "text-red-500"],
        },
        natural_chinese: "怎么说泰语？",
        grammar_point: "Method questions with ยังไง",
        key_vocab: {
          พูด: "to speak (verb)",
          "ภาษา-ไทย": "Thai language (noun)",
          "ยัง-ไง": "how (question word)",
        },
      },
      {
        segments: [
          {
            thai: ["ไป"],
            romanized: ["bpai"],
            chinese: "去",
            english: "go to",
            type: "verb",
            color: "text-blue-500",
          },
          {
            thai: ["ตลาด"],
            romanized: ["dtà-làat"],
            chinese: "市场",
            english: "market",
            type: "noun",
            color: "text-red-500",
          },
          {
            thai: ["ยัง", "ไง"],
            romanized: ["yang", "ngai"],
            chinese: "怎么",
            english: "how",
            type: "question word",
            color: "text-green-500",
          },
        ],
        english: "How do you get to the market?",
        english_segments: ["how", "go to", "the market"],
        literal_chinese: {
          text: ["怎么", "去", "市场"],
          colors: ["text-green-500", "text-blue-500", "text-red-500"],
        },
        natural_chinese: "怎么去市场？",
        grammar_point: "Method questions with ยังไง",
        key_vocab: {
          ไป: "to go (verb)",
          ตลาด: "market (noun)",
          "ยัง-ไง": "how (question word)",
        },
      },
    ],
  },
};
